// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phnezypbxiegnmpkxiqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBobmV6eXBieGllZ25tcGt4aXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyMzM1MDcsImV4cCI6MjA3NzgwOTUwN30.9YzV9c18iVda71226R5WqVIBqo6BTT2QZ1f9zD6BHOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});